PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX iisgv: <https://iisg.amsterdam/openarchdeaths1910_1920/vocab/>
PREFIX iisgv2: <https://iisg.amsterdam/openarchdeath/vocab/>
PREFIX gg: <http://www.gemeentegeschiedenis.nl/gg-schema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX bio: <http://purl.org/vocab/bio/0.1/>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>

SELECT   ?municipality  ?mean ?november_1918 ?excess_death_rate
WHERE { 
     
  FILTER(?mean >1)   # to avoid 'division by 0' error
  FILTER(?november_1918 >1)
  FILTER(?month = "11"^^xsd:integer)
  
 
    {
    select ?amco  ?municipality  ?month 
         
     (sum(if(?year = "1918"^^<http://www.w3.org/2001/XMLSchema#int>, 1, 0)) as ?november_1918)
    (sum(if(?year = "1910"^^<http://www.w3.org/2001/XMLSchema#int>, 1, 0)) as ?1910)
    (sum(if(?year = "1911"^^<http://www.w3.org/2001/XMLSchema#int>, 1, 0)) as ?1911)
     (sum(if(?year = "1912"^^<http://www.w3.org/2001/XMLSchema#int>, 1, 0)) as ?1912) 
     (sum(if(?year = "1913"^^<http://www.w3.org/2001/XMLSchema#int>, 1, 0)) as ?1913)  
    (sum(if(?year = "1914"^^<http://www.w3.org/2001/XMLSchema#int>, 1, 0)) as ?1914) 
     (sum(if(?year = "1915"^^<http://www.w3.org/2001/XMLSchema#int>, 1, 0)) as ?1915)
     (sum(if(?year = "1916"^^<http://www.w3.org/2001/XMLSchema#int>, 1, 0)) as ?1916)
     (sum(if(?year = "1917"^^<http://www.w3.org/2001/XMLSchema#int>, 1, 0)) as ?1917)
          {
        
  ?death a bio:Death .
  ?death iisgv:deceased ?deceased .
  ?death bio:date ?date .
  ?death iisgv:event_location ?gemeente .
  ?gemeente gg:amsterdamCode ?amco .
  ?amco gg:identifies  ?gg_gemeente .
  ?gg_gemeente gg:name ?municipality .
  FILTER  NOT EXISTS {
     ?gg_gemeente gg:startDate ?startdate 
        FILTER(?startdate >= "1920-01-01"^^<http://www.w3.org/2001/XMLSchema#date>)
   }
      FILTER  NOT EXISTS {
     ?gg_gemeente gg:endDate ?enddate 
        FILTER(?enddate <= "1920-01-01"^^<http://www.w3.org/2001/XMLSchema#date>)
   }
 
  BIND(year(?date) as ?year)
  BIND(month(?date) as ?month)
   
        }}   
      
  BIND(xsd:float(?1910+?1911+?1912+?1913+?1914+?1915+?1916+?1917)/8 as ?mean)
  BIND(xsd:float(?november_1918/?mean) as ?excess_death_rate)
 
    }
  
ORDER BY DESC (?excess_death_rate)
