PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX hisco: <https://iisg.amsterdam/hisco/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT distinct ?provenance (count(?provenance) as ?prov_count) ?language
WHERE {
	hisco:jobHoard skos:member ?job .
  	?job skos:prefLabel ?label .
    hisco:category skos:member ?hisco.
    OPTIONAL {hisco:job skos:hiddenLabel ?label} .
    ?job prov:wasDerivedFrom ?provenance .
    BIND(lang(?label) AS ?language) .
  	# FILTER(lang(?label) = "nl") . uncomment to filter for a specific language
} group by ?provenance ?language
ORDER BY ?language
