#+Author: Eric de Ruijter
#+Description: Cartoons by Albert Hahn on the struggle for universal suffrage.

PREFIX iisgv: <https://iisg.amsterdam/vocab/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  ?sub rdf:type <https://iisg.amsterdam/vocab/Drawing> .
  ?sub iisgv:topic <https://iisg.amsterdam/authority/topic/12660> .
  ?sub schema:author <https://iisg.amsterdam/authority/person/136339> .
  ?sub schema:description ?desc .
  ?sub foaf:depiction/foaf:thumbnail ?thumb .
  bind('<figure><img src="{{thumb}}"><figcaption>{{desc}}</figcaption></figure>' as ?widget)
} LIMIT 10
