PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX catastodim: <https://iisg.amsterdam/catasto/dimension/>
PREFIX catasto: <https://iisg.amsterdam/catasto/>
PREFIX catastoregion: <https://iisg.amsterdam/catasto/code/NUMSER/>


SELECT  ?age (count(distinct ?florence) as ?n_florence)  (count(distinct ?contado) as ?n_contado)

WHERE {{
    ?florence a catasto:individual .
    ?florence catastodim:age ?age .
    ?florence catastodim:inHousehold /catastodim:NUMSER catastoregion:1 .
}
  UNION {
    ?contado a catasto:individual .
    ?contado catastodim:age ?age .
    ?contado catastodim:inHousehold /catastodim:NUMSER catastoregion:6 .
    } 
  FILTER(?age > 22)
}

  
ORDER BY ASC (?age)
