PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX catastodim: <https://iisg.amsterdam/catasto/dimension/>
PREFIX catasto: <https://iisg.amsterdam/catasto/>
PREFIX catastoregion: <https://iisg.amsterdam/catasto/code/NUMSER/>

SELECT ?occupation (count(distinct ?sub) as ?n_hh) (round(avg(?wealth)) as ?avg_wealth_rounded) (avg(?hh_members) as ?avg_hh_members) WHERE
{ SELECT (count(?members) as ?hh_members) ?occupation ?sub ?wealth

WHERE {
 
?sub catastodim:householdMember ?members ;
     catastodim:TOTAL ?wealth ;
     catastodim:DEDUCT ?debt ;
     catastodim:CREANCE ?pubcred ;
     catastodim:CREDPUB ?privcred ;
     catastodim:NUMSER catastoregion:1 .
?sub catastodim:METIER ?occ .
?occ skos:altLabel ?occupationlabel .
  
 BIND(STR(?occupationlabel) as ?occupation)
 FILTER(?wealth > 1500)
  }}

 ORDER BY  DESC(?n_hh)
 LIMIT 10
