PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX catastodim: <https://iisg.amsterdam/catasto/dimension/>
PREFIX catasto: <https://iisg.amsterdam/catasto/>


SELECT ?total_assets ?occupation ?family_lastname
WHERE {
 
 ?sub a catasto:household ;
 	catastodim:NUMSER / skos:prefLabel ?regionlabel ;
 	catastodim:TOTAL ?assets ; 
	catastodim:METIER ?occ .
 ?occ skos:altLabel ?occupationlabel .
 ?sub catastodim:NOMFAM ?familyname .
  
  
	BIND(STR(?assets) as ?total_assets)
  	BIND(CONCAT(UCASE(SUBSTR(?familyname, 1, 1)), LCASE(SUBSTR(?familyname, 2))) as ?name)
  	BIND(STR(?name) as ?family_lastname)
  	BIND(STR(?occupationlabel) as ?occupation)
} 
ORDER BY DESC (?assets)
LIMIT 10
