# Same can be done with `iisg:dateOfManufacture' and
# `iisg:dateOfPublication' or `schema:inLanguage' 5 strings for
# datasets of inLanguage, others all use `lexvo:iso639-3:...' are also
# connected with `dc:language'.

prefix iisg: <https://iisg.amsterdam/vocab/>
select ?label (count(?item) as ?n) {
  ?item iisg:dateOfPublication ?date.
  bind(datatype(?date) as ?d)
  bind(strafter(str(?d), "#") as ?label)
}
group by ?label
order by desc(?n)
