prefix schema: <http://schema.org/>
select
  ?name
  (replace(?n,'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.') as ?n)
{
  {
    select ?name (count(distinct ?person) as ?n) {
      ?person a schema:Person;
              schema:name ?name.
    }
    group by ?name
    order by desc(?n)
    limit 100
  }
}
