prefix iisg: <https://iisg.amsterdam/vocab/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sc: <http://purl.org/science/owl/sciencecommons/>
prefix schema: <http://schema.org/>
select
  ?name
  (count(?work) as ?number_of_works)
  (count(distinct ?person_id) as ?number_of_occurrences)
  from <https://iisg.amsterdam/graph/collection>
{
  ?work schema:author ?person_id.
  ?person_id schema:name ?name.
  optional{ ?person_id iisg:titleOrWord ?title_or_word. }
  optional{ ?person_id iisg:numeration ?numeration. }
}
group by ?name ?title_or_word ?numeration
order by desc(?number_of_works) desc(?number_of_occurrences)
limit 100
