PREFIX sc: <http://purl.org/science/owl/sciencecommons/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX iisg: <https://iisg.amsterdam/vocab/>


SELECT ?name ?title_or_word ?numeration (group_concat(distinct ?person_id; separator=" ") as ?concat) (count(distinct ?person_id) as ?number_of_occ) (count(?work) as ?number_of_works)
FROM <https://iisg.amsterdam/graph/collection>
{
  ?work schema:author ?person_id.
  ?person_id schema:name ?name.
  OPTIONAL{?person_id iisg:titleOrWord ?title_or_word.}
  OPTIONAL{?person_id iisg:numeration ?numeration.}
}	

group by ?name ?title_or_word ?numeration 
order by desc(?number_of_occ) desc(?number_of_works)
limit 100
