PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX loc: <http://id.loc.gov/vocabulary/relators/>
PREFIX dctype: <http://purl.org/dc/dcmitype/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org/>
Select *
{
  ?collection_id rdf:type dctype:Text.
  ?collection_id loc:cre ?event_1, ?event_2.
  ?event_1 a schema:Event.
  ?event_2 a schema:Event.
  ?event_1 schema:name ?event_name1.
  ?event_2 schema:name ?event_name2.
  filter(?event_1 > ?event_2)
  filter(?event_name2 = ?event_name1)
}

limit 100