prefix buurt: <https://data.pdok.nl/cbs/id/buurt/>
prefix gemeente: <https://data.pdok.nl/cbs/id/gemeente/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix vocab: <https://data.pdok.nl/cbs/vocab/>
select ?wkt ?wktLabel {
  ?feature geo:sfWithin/geo:sfWithin gemeente:2016GM0363 .
  ?feature geo:hasGeometry/geo:asWKT ?wkt ; rdfs:label ?label .
  bind(concat("<p>",str(?label),"<br>",str(?feature),"</p>") as ?wktLabel)
}
limit 1000
