prefix das: <https://demo.triply.cc/huygens-ing/dutch-asiatic-shipping/>
prefix geonames: <http://www.geonames.org/ontology#>
prefix ship: <https://demo.triply.cc/huygens-ing/dutch-asiatic-shipping/id/ship/>
select
  (str(?voc_kamer) as ?voc_kamer)
  (str(?scheepsnaam) as ?scheepsnaam)
  (str(?schipper) as ?schipper)
  (str(?vertrekplaats) as ?vertrekplaats)
  (str(?vertrekdatum) as ?vertrekdatum)
  (str(?aankomstplaats) as ?aankomstplaats)
  (str(?aankomstdatum) as ?aankomstdatum)
  (str(?duur_in_dagen) as ?duur_in_dagen)
{
  bind(ship:DAS_ship0010 as ?schip) # 't Vliegend Hart' == DAS_ship0010
  ?voy das:shipid ?schip.
  optional { ?voy das:voychamber ?voc_kamer. }
  optional { ?schip das:shipname ?scheepsnaam. }
  optional { ?voy das:voymaster ?schipper. }
  optional { ?voy das:voydepartureplaceid/das:toponym_original ?vertrekplaats. }
  optional { ?voy das:voydepartureedtf ?vertrekdatum. }
  optional { ?voy das:voyarrivalplaceid/das:toponym_original ?aankomstplaats. }
  optional { ?voy das:voyarrivaldateedtf ?aankomstdatum. }
  bind((?aankomstdatum-?vertrekdatum)/(24*60*60) as ?duur_in_dagen)
}
order by ?vertrekdatum
