prefix lib: <http://purl.org/library/>
prefix schema: <http://schema.org/>
select
  ?werk
  (str(?author) as ?auteur)
  (str(?title) as ?titel)
  (str(?published) as ?publicatiedatum)
{
  ?werk
    schema:creator/schema:name ?author;
    schema:datePublished ?published;
    schema:name ?title.
  filter(regex(?title,"VOC"))
}
order by desc(?published)
