PREFIX geonames: <http://www.geonames.org/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX na: <http://archief.nl/def/>
PREFIX plaats-na: <http://archief.nl/NL-HaNA/id/plaats/>
PREFIX das: <http://purl.org/collections/nl/dss/das/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX def: <https://demo.triply.cc/huygens-ing/voc-opvarenden-verrijkingen-carrieres/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX voyage1: <http://archief.nl/NL-HaNA/id/reis/VoyageDas:>
PREFIX voyage2: <https://demo.triply.cc/huygens-ing/voc-opvarenden-verrijkingen-carrieres/id/dasTrip/>

SELECT ?shape ?shapeColor ?shapeLabel  WHERE {
  BIND(voyage1:2978.2 as ?tripID1)
  BIND(voyage2:2978.2 as ?tripID2)
  ?tripID1 na:voyageHasPassenger ?personNa.
  ?personNa na:hasProfession ?beroep;
            rdfs:label ?name;
            <http://rdf.histograph.io/originatedFrom> ?plaats.
  BIND(replace(str(?beroep), "http://archief.nl/NL-HaNA/id/beroep/", "") as ?beroepStr)
  OPTIONAL {
    ?personVer def:voynumberdas ?tripID2;
               def:fullname ?name ;
               def:rank ?rang;
               def:ExternalHiscoIdentifier ?hisco;
               def:ExternalIdentifier ?geo;
               def:placeorigin ?place;
               def:scanpermalink ?handle.
    OPTIONAL {
      ?personVer def:lon_arcgis ?lon ;
                 def:lat_arcgis ?lat .
    }
    ?hisco a <https://iisg.amsterdam/hisco/code/HISCO>;
           skos:prefLabel ?work.
    BIND('<a target="_blank" noreferrer href="https://demo.triply.cc/maritieme-musea/maritieme-musea/browser?resource=' as ?href)
    BIND(concat("Volledige naam: ",?href, ?personVer,'">' ,?name, "</a><br>",
              " Geboorte Locatie: ",?href, ?geo,'">' ,?place, "</a><br>",
              " HISCO: ",?href, ?hisco,'">', ?work, "</a><br>",
              " Rank: ", ?rang, "<br>") as ?shapeLabel)

    BIND(strdt(concat("POINT (",REPLACE(str(?lon),",",".")," ",REPLACE(str(?lat),",","."),")"),"http://www.openlinksw.com/schemas/virtrdf#Geometry") as ?shape)
    BIND(if(STRSTARTS(STR(?hisco), "https://iisg.amsterdam/hisco/code/hisco/583"), "green", "blue") as ?shapeColor)
  }
} GROUP BY ?shape ?shapeColor ?shapeLabelPart1
