PREFIX cliovocab: <https://iisg.amsterdam/clio/vocab/>
PREfix sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>

SELECT * WHERE {
  ?sub cliovocab:GDP_per_Capita ?gdp_per_country .
  ?sub sdmxdim:refPeriod "1900-01-01"^^xsd:gYear .
}
